import { GridApi } from "ag-grid-community";
import { ATN } from "antlr4ts/atn/ATN";
import { CharStream } from "antlr4ts/CharStream";
import { Lexer } from "antlr4ts/Lexer";
import { Vocabulary } from "antlr4ts/Vocabulary";
export declare class FormulaLexer extends Lexer {
    static readonly T__0 = 1;
    static readonly T__1 = 2;
    static readonly T__2 = 3;
    static readonly T__3 = 4;
    static readonly T__4 = 5;
    static readonly INT = 6;
    static readonly MUL = 7;
    static readonly DIV = 8;
    static readonly PLUS = 9;
    static readonly MINUS = 10;
    static readonly COMMA = 11;
    static readonly DQUOTE = 12;
    static readonly TRUE = 13;
    static readonly FALSE = 14;
    static readonly IDENT = 15;
    static readonly EQ = 16;
    static readonly NEQ = 17;
    static readonly LT = 18;
    static readonly LTE = 19;
    static readonly GT = 20;
    static readonly GTE = 21;
    static readonly channelNames: string[];
    static readonly modeNames: string[];
    static readonly ruleNames: string[];
    private static readonly _LITERAL_NAMES;
    private static readonly _SYMBOLIC_NAMES;
    static readonly VOCABULARY: Vocabulary;
    get vocabulary(): Vocabulary;
    gridApi: GridApi;
    constructor(input: CharStream);
    get grammarFileName(): string;
    get ruleNames(): string[];
    get serializedATN(): string;
    get channelNames(): string[];
    get modeNames(): string[];
    static readonly _serializedATN: string;
    static __ATN: ATN;
    static get _ATN(): ATN;
}
